Add mod salary
saltswap/salt-contracts pull request #3
Opened 2021-03-02 21:30 UTC by saltPink

2021-03-02 21:36 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +    function addMod(address _mod, _claimPerBlock) public onlyOwner {
Missing type for `_claimPerBlock`?

2021-03-02 21:37 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +        require(_amount <= paymentToken.balanceOf(address(this)), 'not enough token');
not needed, safeTransfer already does that.

2021-03-02 21:38 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +        if (claimableBlocks > 0 && supply > 0) {
supply check not needed, if there isn't enough, it should return an error.

2021-03-02 21:38 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +            paymentToken.safeTransferFrom(address(msg.sender), address(this), reward);
should be `paymentToken.transfer(address(msg.sender), reward)`;

2021-03-02 21:40 UTC, saltPink commented on contracts/ModSalary.sol
> +        if (claimableBlocks > 0 && supply > 0) {
this is a "view", should return 0

2021-03-02 21:40 UTC, nebulacrypto requested changes
changes required

2021-03-02 21:44 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +        if (claimableBlocks > 0 && supply > 0) {
it should return `claimablePayment`, whether the contract has enough tokens to claim is a different story.

2021-03-02 21:45 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +        emit Deposit(_mod, _claimPerBlock);
To further automate this, this contract should accept and end block as well, and transfer enough SALT to pay for all the blocks.

2021-03-02 21:47 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +    function pendingReward(address _user) external view returns (uint256) {
public, not external.

2021-03-04 11:43 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +        }
This can be removed, if claimableBlocks is 0, the multiplication above will result in 0 too.

2021-03-04 11:44 UTC, nebulacrypto commented on contracts/ModSalary.sol
> +            return claimablePayment;
if can be removed, if claimableBlocks is 0, multiplication above will be 0 as well.

2021-03-04 11:45 UTC, nebulacrypto approved these changes

2021-03-04 14:44 UTC, merged